FROM quay.io/centos/centos:stream9

RUN dnf install -y dnf-plugins-core \
    && dnf copr enable -y ovirt/ovirt-master-snapshot \
    && dnf install -y ovirt-release-master \
    && dnf config-manager --enable crb \
RUN dnf install -y \
        createrepo_c \
        dnf-utils \
        git \
        gzip \
        make \
        rpm-build \
        tar \
COPY containerroot /
