FROM quay.io/centos/centos:stream8

# Install oVirt repositories
RUN dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-8 \
    && dnf install -y ovirt-release-master
# Configure CS8 repositories
RUN dnf config-manager --enable powertools \
    && dnf module enable -y pki-deps javapackages-tools

# Install required packages
RUN dnf install -y \
        createrepo_c \
        dnf-utils \
        git \
        gzip \
        make \
        rpm-build \
        tar
COPY containerroot /
