FROM quay.io/centos/centos:stream8

RUN dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-8 \
    && dnf install -y ovirt-release-master \
    && dnf config-manager --enable powertools \
    && dnf module enable -y pki-deps javapackages-tools \
RUN dnf install -y \
        createrepo_c \
        dnf-utils \
        git \
        gzip \
        make \
        rpm-build \
        tar \
COPY containerroot /
